spring:
  application:
    name: configserver
  profiles:
    active: native
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
  cloud:
    config:
      server:
        native:
          search-location: file:///C:/Users/pc/Desktop/Ecom-Microservices/Ecommerece-Microservices with Spring Cloud Server and Client/config
server:
  port: 8888

management:
  endpoints:
    web:
      exposure:
        include: "*"