spring:
  cloud:
    gateway:
      routes:
        - id: product-service
          #          uri: http://localhost:8081
          uri: lb://PRODUCT-SERVICE
          predicates:
#            - Path=/api/products/**
            - Path=/products/**       # without /api path
          filters:
            - "RewritePath=/products(?<segment>/?.*),/api/products${segment}"
        - id: user-service
          #          uri: http://localhost:8082
          uri: lb://USER-SERVICE
          # as these port can be change so use eureka and service should be load balanced so use lb://service name and same will do for other services also
          predicates:
#            - Path=/api/users/**
            - Path=/users/**    # without /api path
          filters:
            - "RewritePath=/users(?<segment>/?.*),/api/users${segment}"
        - id: order-&-cart-service
          #          uri: http://localhost:8083
          uri: lb://ORDER-CART-SERVICE
          predicates:
#            - Path=/api/orders/**, /api/cart/**
            - Path=/orders/**,/cart/**     # without /api path
          filters:
            - "RewritePath=/(?<segment>.*),/api/${segment}"
        - id: eureka-server
          uri: http://localhost:8761
          predicates:
            - Path=/eureka/main
          filters:
            - SetPath=/
        - id: eureka-server-static
          uri: http://localhost:8761
          predicates:
            - Path=/eureka/**
        # want to handel the services paths by java configuration written in GatewayConfig then comment the whole
        # above part and uncomment the configuration and bean annotation in GatewayConfig

server:
  port: 8080

#logging:
#  level:
#    root: info
#    org.springframework.cloud.gateway.route.RouteDefinitionLocator: INFO
#    org.springframework.cloud.gateway: TRACE

management:
  endpoints:
    web:
      exposure:
        include: "*"
  tracing:
    sampling:
      probability: 1.0