spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/order
    username: embarkx
    password: embarkx
  jpa:
    database: POSTGRESQL
    show-sql: true
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    properties:
      hibernate:
        format_sql: true
server:
  port: 8083
