spring:
  application:
    name: configserver
  profiles:
    active: native
#  rabbitmq:
#    host: localhost
#    port: 5672
#    username: guest
#    password: guest
  # ABOVE WHEN USING THE DOCKER INSTANCE RABBITMQ

  #NOW USING THE CLOUDAMQP RABBITMQ CLOUD
  rabbitmq:
    host: ${RABBITMQ_HOST:localhost}
    port: ${RABBITMQ_PORT:5672}
    username: ${RABBITMQ_USERNAME:guest}
    password: ${RABBITMQ_PASSWORD:guest}
    virtual-host: ${RABBITMQ_VHOST:guest}
    connection-timeout: 30000
    ssl:
      enabled: true
  cloud:
    config:
      server:
        native:
          search-location: file:///C:/Users/pc/Desktop/Ecom-Microservices/Ecommerece-Microservices with Spring Cloud Server and Client/config
server:
  port: 8888

management:
  endpoints:
    web:
      exposure:
        include: "*"