spring:
  application:
    name: config-demo

# this basically used for switching the profile between dev or prod and activating one will overwrite the default data
# if no one is active then the default data will show
#  profiles:
#    active: prod

#build:
#  id: 122
#  version: 2.2.2
#  name: "Default-Build"
#  type: "Default Build"

# using placeholder that comes from the intellij environment variable
#build:
#  id: ${ID}
#  version: ${VERSION}
#  name: ${NAME}
#  type: "Default Build"

build:
  id: ${ID} # through the command line argument given in edit configuration

#  commands for making the jar file  -> mvnw clean package
#  commands for running the jar file  -> java -jar target\here jar file name

# BUILD_ID=124;BUILD_VERSION=1.0.0;BUILD_NAME=ThroughIntellijConfiguration
# THIS USED TO GIVE THE ENVIRONMENT VARIABLES

#by placeholders the environment variables given
# ID=9999;VERSION=1.0.0;NAME=IntellijEnvironmentVariable
