#spring:
#  application:
#    name: consumer
#  kafka:
#    consumer:
#      bootstrap-server: localhost:9092
#      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
#      value-deserializer: org.springframework.kafka.support.serializer.ErrorHandlingDeserializer
#      properties:
#        spring.deserializer.value.delegate.class: org.springframework.kafka.support.serializer.JsonDeserializer
#        spring.json.trusted.packages: "*"
#        spring.json.value.default.type: com.kafka.consumer.RiderLocation
#
#server:
#  port: 8081

spring:
  application:
    name: consumer

  cloud:
    function:
      definition: processRiderLocation; processRiderStatus
    stream:
      function:
        definition: processRiderLocation; processRiderStatus
      bindings:
        processRiderLocation-in-0:
          destination: my-topic
          group: rider-location-grp
          content-type: application/json
        processRiderStatus-in-0:
          destination: my-new-topic-2
          group: rider-status-grp
          content-type: text/plain
      kafka:
        binder:
          brokers: localhost:9092

server:
  port: 8081
