spring:
  application:
    name: notification
#  rabbitmq:
#    host: localhost
#    port: 5672
#    username: guest
#    password: guest
  # ABOVE WHEN USING THE DOCKER INSTANCE RABBITMQ

  #NOW USING THE CLOUDAMQP RABBITMQ CLOUD
  rabbitmq:
    host: ${RABBITMQ_HOST:localhost}
    port: ${RABBITMQ_PORT:5672}
    username: ${RABBITMQ_USERNAME:guest}
    password: ${RABBITMQ_PASSWORD:guest}
    virtual-host: ${RABBITMQ_VHOST:guest}
    connection-timeout: 30000
    ssl:
      enabled: true

  cloud:
    function:
      definition: orderCreated
    stream:
      function:
        definition: orderCreated
      bindings:
        orderCreated-in-0:
          destination: order.exchange.new
          group: notification-group
          content-type: application/json
server:
  port: 8084

rabbitmq:
  exchange:
    name: order.exchange
  queue:
    name: order.queue
  routing:
    key: order.tracking
