spring:
  application:
    name: configserver
#  WHEN USING THE FILE BASED CONFIGURATION
  profiles:
    active: native
  cloud:
    config:
      server:
        native:
#          search-location: classpath:/config
#          this i have changed because the classpath is static
          search-location: file:///C:/Users/pc/Desktop/Ecom-Microservices/Configuration Mangement for Microservices/config

#### because
#Spring Cloud Config has two main modes for native files:
#
#  Classpath mode
#  spring.cloud.config.server.native.search-locations=classpath:/config
#  → Reads files from inside the JAR (unchangeable at runtime)
#
#  File system mode
#  spring.cloud.config.server.native.search-locations=file:///path/to/config
#  → Reads from disk every time, so changes are visible immediately
#
#  Right now, I am using in mode 1, which is static.
# that's why the refresh won't work right now so for forking that i changed the search-location



#    WHEN USING MYSQL DATABASE
#  profiles:
#    active: jdbc
#  datasource:
#    url: jdbc:mysql://localhost:3306/configdb
#    username: root
#    password: mysql@#8456
#    driver-class-name: com.mysql.cj.jdbc.Driver
#  cloud:
#    config:
#      server:
#        jdbc:
##          sql: SELECT PROP_KEY, PROP_VALUE from PROPERTIES where APPLICATION="config-demo" and PROFILE="dev" and LABEL="main"
##          THIS ABOVE IS THE ORIGINAL SQL
#
#          sql: "SELECT PROP_KEY, PROP_VALUE from PROPERTIES where APPLICATION=? and PROFILE=? and LABEL=?"
#          default-label: main
#    THIS WHEN WE USING GIT REPOSITORY FOR THE CONFIGURATIONS
#  cloud:
#    config:
#      server:
#        git:
#          uri: https://github.com/rio-aman/spring-cloud-server-app-configuration
#          username: ${GIT_USER}
#          password: ${GIT_TOKEN}
server:
  port: 8888

#using the aes (advanced encryption standard) for encrypting and decrypting the secret messages
#encrypt:
#  key: "0E23242EA6D3D706"

#now using keytool or keystore and rsa key pair
encrypt:
  key-store:
    location: config-server.jks
    password: mypass
    alias: config-server-key